// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatePickerController from "./date_picker_controller"
application.register("date-picker", DatePickerController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DynamicFieldsController from "./dynamic_fields_controller"
application.register("dynamic-fields", DynamicFieldsController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HighlightController from "./highlight_controller"
application.register("highlight", HighlightController)

import ImageUploadController from "./image_upload_controller"
application.register("image-upload", ImageUploadController)

import LangSelectionController from "./lang_selection_controller"
application.register("lang-selection", LangSelectionController)

import NationalityTwoController from "./nationality_two_controller"
application.register("nationality-two", NationalityTwoController)

import PeopleController from "./people_controller"
application.register("people", PeopleController)

import PeopleSkillsController from "./people_skills_controller"
application.register("people-skills", PeopleSkillsController)

import PeopleSkillsFilterController from "./people_skills_filter_controller"
application.register("people-skills-filter", PeopleSkillsFilterController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SkillsEmptySpaceController from "./skills_empty_space_controller"
application.register("skills-empty-space", SkillsEmptySpaceController)

import SkillsFilterController from "./skills_filter_controller"
application.register("skills-filter", SkillsFilterController)

import SkillsetSelectedController from "./skillset_selected_controller"
application.register("skillset-selected", SkillsetSelectedController)
