// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatePickerController from "./date_picker_controller"
application.register("date-picker", DatePickerController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DynamicFieldsController from "./dynamic_fields_controller"
application.register("dynamic-fields", DynamicFieldsController)

import HighlightController from "./highlight_controller"
application.register("highlight", HighlightController)

import ImageUploadController from "./image_upload_controller"
application.register("image-upload", ImageUploadController)

import LangSelectionController from "./lang_selection_controller"
application.register("lang-selection", LangSelectionController)

import NationalityTwoController from "./nationality_two_controller"
application.register("nationality-two", NationalityTwoController)

import ProfileTabController from "./profile_tab_controller"
application.register("profile-tab", ProfileTabController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SkillLevelController from "./skill_level_controller"
application.register("skill-level", SkillLevelController)

import SkillsFilterController from "./skills_filter_controller"
application.register("skills-filter", SkillsFilterController)

import DropdownLinksController from "./dropdown_controller"
application.register("dropdown", DropdownLinksController)

import SkillsLevelController from "./skill_level_controller"
application.register("skills-level", SkillsLevelController)

import SkillsEmptySpaceController from "./skills_empty_space_controller"
application.register("skills-empty-space", SkillsEmptySpaceController)

import PeopleSkillsFilterController from "./people_skills_filter_controller"
application.register("people-skills-filter", PeopleSkillsFilterController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)
