// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownLinksController from "./dropdown_controller"
application.register("dropdown", DropdownLinksController)
import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)
import NationalityTwoController from "./nationality_two_controller"
application.register("nationality-two", NationalityTwoController)