
repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Scan push for secrets.
        entry: sudo bash -c 'trufflehog git file://. --since-commit HEAD --no-verification --fail'
        language: system
        stages: ["pre-commit", "pre-push"]