repos:
  - repo: local
    hooks:
      - id: trufflehog-docker
        name: TruffleHog (Docker)
        description: Detect secrets in your data.
        entry: bash -c 'docker run --rm -v "$(pwd):/workdir" trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --no-verification --fail'
        language: system
        stages: [pre-commit, pre-push]