require: rubocop-rails
AllCops:
  DisplayCopNames: true
  Exclude:
    - Rakefile
    - db/**/*
    - config/**/*
    - lib/tasks/**/*
    - bin/**/*
    - spec/**/*
    - vendor/**/*
    - tmp/**/*
    - frontend/**/*
    - node_modules/**/*


Metrics/AbcSize:
  Max: 17
  Severity: error

Metrics/ClassLength:
  Max: 200
  Severity: error

Metrics/CyclomaticComplexity:
  Max: 6
  Severity: error

Layout/LineLength:
  Max: 100
  Severity: error

Metrics/MethodLength:
  Max: 10
  Severity: error

Metrics/ModuleLength:
  Max: 200
  Severity: error

Metrics/ParameterLists:
  Max: 4
  Severity: warning

Rails:
  Enabled: true

# Keep for now, easier with superclass definitions
Style/ClassAndModuleChildren:
  Enabled: false

# The ones we use must exist for the entire class hierarchy.
Style/ClassVars:
  Enabled: false

# map instead of collect, reduce instead of inject.
# Probably later
Style/CollectionMethods:
  Enabled: false

# Well, well, well
Style/Documentation:
  Enabled: false

# Probably later
Layout/DotPosition:
  Enabled: false

# Missing UTF-8 encoding statements should always be created.
Style/Encoding:
  Severity: error

# That's no huge stopper
Layout/EmptyLines:
  Enabled: false

# We thinks that's fine for specs
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# We thinks that's fine
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# We thinks that's fine
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# We thinks that's fine
Layout/MultilineOperationIndentation:
  Enabled: false

# But probably more readable...
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Keep single line bodys for if and unless
Style/IfUnlessModifier:
  Enabled: false

# We thinks that's fine
HasAndBelongsToMany:
  Enabled: false

# We think that's the developers choice
Rails/Delegate:
  Enabled: false

# We think that's the developers choice
Rails/SkipsModelValidations:
  Enabled: false
 
Rails/UniqueValidationWithoutIndex:
  Enabled: false

# with the use of controller-abstraction via dry_crud, this is intended
Rails/LexicallyScopedActionFilter:
  Enabled: false

# We thinks that's fine
Style/EmptyMethod:
  Enabled: false

# just false positives for 0.51.0
Style/MixinUsage:
  Enabled: false

# Not sure if this is really an established community standard
Style/PercentLiteralDelimiters:
  Enabled: false

# We thinks that's fine
Style/RegexpLiteral:
  Enabled: false

# We thinks that's fine
Style/SymbolArray:
  Enabled: false

# We think that's the developers choice
Style/SymbolProc:
  Enabled: false

# Probably later
Style/GuardClause:
  Enabled: false

# We think that's fine
Style/SingleLineBlockParams:
  Enabled: false

# We think that's fine
Style/HashSyntax:
  Enabled: false
