services:
  rails:
    container_name: rails
    tty: true
    stdin_open: true
    env_file: .env
    image: skills-dev/rails
    environment:
      - RAILS_DB_HOST=postgres
      - GEM_PATH=/usr/local/bundle:/opt/bundle
    build:
      context: ./config/docker/development
      dockerfile: Rails.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - ./config/docker/development/home/rails:/home/developer
      - bundle:/opt/bundle
    profiles: ["", "all"]
    init: true
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://127.0.0.1:3000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    depends_on:
      postgres:
        condition: service_healthy

  test:
    container_name: test
    tty: true
    stdin_open: true
    env_file: .env
    image: skills-test/rails
    environment:
      - RAILS_DB_HOST=postgres
      - RAILS_ENV=test
      - GEM_PATH=/usr/local/bundle:/opt/bundle
    build:
      context: ./config/docker/test
      dockerfile: Test.dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/myapp
      - ./config/docker/test/home/rails:/home/test
      - bundle_test:/opt/bundle
    profiles: ["all", "test"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["all", "", "test"]

  assets:
    container_name: assets
    image: skills-dev/rails
    environment:
      - RAILS_ENV=development
      - RAILS_DB_HOST=postgres
      - SKIP_RAILS_MIGRATIONS=true
      - SKIP_RAILS_SEED=true
    command: bash -c "bin/assets && sleep infinity"
    volumes:
      - .:/myapp
      - bundle:/opt/bundle
    depends_on:
      rails:
        condition: service_healthy
    profiles: ["all", ""]

  worker:
    container_name: worker
    image: skills-dev/rails
    environment:
      - RAILS_DB_HOST=postgres
      - RAILS_ENV=development
      - SKIP_RAILS_MIGRATIONS=true
      - SKIP_RAILS_SEED=true
    env_file: .env
    restart: on-failure
    command: rails jobs:work
    volumes:
      - .:/myapp
      - bundle:/opt/bundle
    depends_on:
      postgres:
        condition: service_healthy
      rails:
        condition: service_healthy
    profiles: ["all", ""]

volumes:
  postgres:
  bundle:
  bundle_test: