# encoding: utf-8

require Rails.root.join('db', 'seeds', 'support', 'person_seeder')

seeder = PersonSeeder.new

names = ['Jorah Mormont',
         'Tyrion Lannister',
         'Stannis Baratheon',
         'Varys Baratheon',
         'Gendry Mormot',
         'Gregor Clegane',
         'Jon Snow',
         'Cersei Lannister',
         'Samwell Tarly',
         'Ned Stark',
         'Melisandre',
         'Theon Greyjoy',
         "Jaqen H'ghar",
         'Jaime Lannister',
         'Joffrey Baratheon',
         'Sandor Clegane',
         'Bob Stark',
         'Daenerys Targaryen',
         'Davos Seaworth',
         'Arya Stark',
         'Robb Stark',
         'Sansa Stark',
         'Bran Stark',
         'Catelyn Stark',
         'Hodor Seaworth',
         'Tywin Lannister',
         'Margaery Tyrell',
         'Brienne of Tarth',
         'Renly Baratheon',
         'Missandei',
         'Tormund Giantsbane',
         'Bronn Giantsbane',
         'Podrick Payne',
         'Tommen Baratheon',
         'Ramsay Bolton',
         'Oberyn Martell',
         'Petyr Baelish',
         'Ygritte Bolton',
         'Jorah Mormont',
         'Tyrion Lannister',
         'Stannis Baratheon',
         'Varys H ghar',
         'Gendry Payne',
         'Gregor Clegane',
         'Jon Snow',
         'Cersei Lannister',
         'Samwell Tarly',
         'Ned Stark',
         'Melisandre',
         'Theon Greyjoy',
         "Jaqen H'ghar",
         'Jaime Lannister',
         'Joffrey Baratheon',
         'Sandor Clegane',
         'Bob Stark',
         'Daenerys Targaryen',
         'Davos Seaworth',
         'Arya Stark',
         'Robb Stark',
         'Sansa Stark',
         'Bran Stark',
         'Catelyn Stark',
         'Hodor Stark',
         'Tywin Lannister',
         'Margaery Tyrell',
         'Brienne of Tarth',
         'Renly Baratheon',
         'Missandei Lannister',
         'Tormund Giantsbane',
         'Bronn Giantsbane',
         'Podrick Payne',
         'Tommen Baratheon',
         'Ramsay Bolton',
         'Oberyn Martell',
         'Petyr Baelish',
         'Ygritte Martell',
         'Jorah Mormont',
         'Tyrion Lannister',
         'Stannis Baratheon',
         'Varys Payne',
         'Gendry Baelish',
         'Gregor Clegane',
         'Jon Snow',
         'Cersei Lannister',
         'Samwell Tarly',
         'Ned Stark',
         'Melisandre',
         'Theon Greyjoy',
         "Jaqen H'ghar",
         'Jaime Lannister',
         'Joffrey Baratheon',
         'Sandor Clegane',
         'Bob Stark',
         'Daenerys Targaryen',
         'Davos Seaworth',
         'Arya Stark',
         'Robb Stark',
         'Sansa Stark',
         'Bran Stark',
         'Catelyn Stark',
         'Hodor Lannister',
         'Tywin Lannister',
         'Margaery Tyrell',
         'Brienne of Tarth',
         'Renly Baratheon',
         'Missandei Tyrell',
         'Tormund Giantsbane',
         'Bronn of Tarth',
         'Podrick Payne',
         'Tommen Baratheon',
         'Ramsay Bolton',
         'Oberyn Martell',
         'Petyr Baelish',
         'Ygritte Bolton',
         'Jorah Mormont',
         'Tyrion Lannister',
         'Stannis Baratheon',
         'Varys Martell',
         'Gendry Mormot',
         'Gregor Clegane',
         'Jon Snow',
         'Cersei Lannister',
         'Samwell Tarly',
         'Ned Stark',
         'Melisandre Snow',
         'Theon Greyjoy',
         "Jaqen H'ghar",
         'Jaime Lannister',
         'Joffrey Baratheon',
         'Sandor Clegane',
         'Bob Stark',
         'Daenerys Targaryen',
         'Davos Seaworth',
         'Arya Stark',
         'Robb Stark',
         'Sansa Stark',
         'Bran Stark',
         'Catelyn Stark',
         'Hodor Stark',
         'Tywin Lannister',
         'Margaery Tyrell',
         'Brienne of Tarth',
         'Renly Baratheon',
         'Missandei',
         'Tormund Giantsbane',
         'Bronn Payne',
         'Podrick Payne',
         'Tommen Baratheon',
         'Ramsay Bolton',
         'Oberyn Martell',
         'Petyr Baelish',
         'Ygritte']

seeder.seed_people(names)
