# encoding: utf-8

require Rails.root.join('db', 'seeds', 'support', 'person_seeder')

seeder = PersonSeeder.new

names = ['Jorah Mormont',
         'Tyrion Lannister',
         'Stannis Baratheon',
         'Varys',
         'Gendry',
         'Gregor Clegane',
         'Jon Snow',
         'Cersei Lannister',
         'Samwell Tarly',
         'Ned Stark',
         'Melisandre',
         'Theon Greyjoy',
         "Jaqen H'ghar",
         'Jaime Lannister',
         'Joffrey Baratheon',
         'Sandor Clegane',
         'Bob Stark',
         'Daenerys Targaryen',
         'Davos Seaworth',
         'Arya Stark',
         'Delilah Curneen',
         'Dorris Duchateau',
         'Boycie Kopps',
         'Conrado Lancaster',
         'Elsi Summerlee',
         'Ariella Bradden',
         'Ethelred Fourcade',
         'Franchot Hanburry',
         'Steffane Tarbin',
         'Arlan Kilgallen',
         'Deina Cotesford',
         'Nikolai Jeandet',
         'Nydia Gilkison',
         'Jacklin Camilleri',
         'Florance Jahan',
         'Agnes Littleover',
         'Roma Milligan',
         'Antonia Andriuzzi',
         'Stesha Bruty',
         'Rolfe McLernon',
         'Loren Woodhouse',
         'Elena Abazi',
         'Sara Fone',
         'Derwin Filoniere',
         'Lacee Lovering',
         'Sammy Bartholomieu',
         'Rodina Skill',
         'Morissa Daenen',
         'Anissa Gettins',
         'Lenee MacSwayde',
         'Barbey Aizic',
         'Eugene Astlett',
         'Maurits McBryde',
         'Katrinka Purslow',
         'Mechelle Throssell',
         'Jordana Tures',
         'Drew Geyton',
         'Kelly Talby',
         'David Chasmer',
         'Byrann Reason',
         'Evvie Shrubb',
         'Wittie Olivie',
         'Gearard Beggio',
         'Roselia Blaskett',
         'Cornelius Benedit',
         'Kari Birrell',
         'Matthew Beadon',
         "Ricca O'Leahy",
         'Mirella Pankethman',
         'Addie Kingstne',
         'Trip Fazakerley',
         'Haleigh McIlroy',
         'Pyotr Schankel',
         'Pansie Blackly',
         'Zsa zsa Stickings',
         'Travus Shewen',
         'Cami Barkus',
         'Dorothee Novotna',
         'Malia Goodwin',
         'Charmion Szanto',
         'Josephina Oseman',
         'Alonzo Thewlis',
         'Lucia Coldicott',
         'Lonnard Cuzen',
         'Marian Jacob',
         'Kare Ewence',
         'Lutero Shieber',
         'Mari Zamorrano',
         'Pearce Matys',
         'Orran Beddingham',
         'Bernadette Halward',
         'Lenna Betteney',
         'Timmie Iorizzi',
         'Agosto Tressler',
         'Carlin Eskriett',
         'Emily Mc Curlye',
         'Dania Maybery',
         'Gradeigh Caseley',
         'Huberto Joseph',
         'Ede Chilver',
         'Fonsie Birkbeck',
         'Alick Kenlin',
         'Gerri Sollon',
         'Caron Stockow',
         'Elmer Scamerden',
         'Clayson Ibarra',
         'Candra McCulley',
         'Juditha Dumblton',
         'Beatrix Henrionot',
         'Rosamund Parvin',
         'Rowen Brigg',
         'Jessie Elloit',
         'Simmonds Sainte Paul',
         'Noelyn Merton',
         'Brigitta Leese',
         'Alena Peever',
         'Ema Zecchini',
         'Cody Bengochea',
         'Rachael Ranner',
         'Kerwin Yardley',
         'Norine Glennard',
         'Ali Lindemann',
         'Berti Guerreru',
         'Sher Shears',
         'Gradeigh Gullyes',
         'Ripley Roome',
         'Law Hulson',
         'Job Dickey',
         'Henryetta Finkle',
         'Eugen McNerlin',
         'Esta Hatch',
         'Gwenore Aspinall',
         'Morganica Sharpus',
         'Patten Keast',
         'Wrennie Paule',
         'Dorrie Permain',
         'Larina Grimsdike',
         'Cinda Smyley',
         'Codie Paddefield',
         'Philippa Durker',
         'Arabel Myton',
         'Byrle MacConnel',
         'Alvis Mulcahy',
         'Cristal Kitto',
         'Lisetta Golby',
         'Matilde Coatham',
         'Clary Marchello',
         'Letti Dalman',
         'Madlin Fradson',
         'Robenia Gravenor']


seeder.seed_people(names)
