version: '2'

services:
  db:
    image: postgres:9.5.7
    container_name: skills_db
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_DB: cv2_production
      POSTGRES_USER: puzzlecv
      POSTGRES_PASSWORD: puzzlecv
  web:
    image: puzzle/skills:latest
    container_name: skills
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      RAILS_DB_HOST: db
      RAILS_SERVE_STATIC_FILES: 1
      #SENTRY_DSN_FRONTEND: '123456'
      HELPLINK: 'https://help.my-skills.test'
      KEYCLOAK_DISABLED: 'true'
