version: '2'

services:
  db:
    image: postgres:9.5.7
    container_name: skills_db
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - psql-prod.env
    environment:
      POSTGRES_USER: skills_production
      POSTGRES_DB: skills_production
  web:
    image: puzzle/skills:latest
    container_name: skills_web
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - psql-prod.env
    environment:
      RAILS_DB_HOST: db
      RAILS_SERVE_STATIC_FILES: 1
      #SENTRY_DSN_FRONTEND: '123456'
      HELPLINK: 'https://help.my-skills.test'
      # EMBER_KEYCLOAK_SERVER_URL: 'keycloak.my-skills.test'
      # EMBER_KEYCLOAK_SECRET: '1234'
      # EMBER_KEYCLOAK_CLIENT_ID: 'test-client-id'
      # EMBER_KEYCLOAK_REALM_NAME: 'realm'
      KEYCLOAK_DISABLED: 1
volumes:
  skills-postgresql:
  skills-store:
