# provider: db

# Keycloak example
provider: openid-connect

oidc:
  client_id: pitc_skills_rails_backend  
  host: keycloak
  host_port: 8180
  host_scheme: https
  secret: 'r609dv7dl50164n4rlga121ott'
  authorization_endpoint: '/auth/realms/pitc/protocol/openid-connect/auth'
  token_endpoint: '/auth/realms/pitc/protocol/openid-connect/token'
  user_subject: preferred_username
  certs_url: https://sso-test.puzzle.ch/auth/realms/skills/protocol/openid-connect/certs
  additional_scopes:
  - email


# ldap example
# provider: ldap
#
# ldap:
#   bind_dn: 'uid=binduser,ou=system,ou=users,dc=acme,dc=itc'
#   bind_password: cGFzc3dvcmQ= # base64 encoded # echo -n 'password' | base64
#   encryption: 'simple_tls'
#   hostnames:
#     - 'ldap.example.com'
#     - 'ldap-fallback.example.com'
#   basename: 'ou=members,ou=users,dc=acme,dc=itc'
#   portnumber: 636
