# provider: db

# Keycloak example
provider: openid-connect

oidc:
  client_id: pitc_skills_rails_backend  
  host: keycloak
  host_port: 8180
  host_scheme: https
  secret: 'r609dv7dl50164n4rlga121ott'
  authorization_endpoint: '/auth/realms/pitc/protocol/openid-connect/auth'
  token_endpoint: '/auth/realms/pitc/protocol/openid-connect/token'
  user_subject: preferred_username
  certs_url: https://sso-test.puzzle.ch/auth/realms/skills/protocol/openid-connect/certs
  additional_scopes:
  - email


# ldap example
# provider: ldap
#
# ldap:
#   bind_dn: 'uid=binduser,ou=system,ou=users,dc=acme,dc=itc'
#   bind_password: cGFzc3dvcmQ= # base64 encoded # echo -n 'password' | base64
#   encryption: 'simple_tls'
#   hostnames:
#     - 'ldap.example.com'
#     - 'ldap-fallback.example.com'
#   basename: 'ou=members,ou=users,dc=acme,dc=itc'
#   portnumber: 636


# eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJJbWFlbzkxQml5WHVMUU1DUnMtYW9PRW5YU2lzQkFVUFludEZXRGxTU21FIn0.eyJleHAiOjE3MDg2OTI3NTcsImlhdCI6MTcwODY5MTg1NywiYXV0aF90aW1lIjoxNzA4NjkxNDEyLCJqdGkiOiIyMzQ5OGQ5ZS0zNjFlLTQ1NGItOTc5NC0xOWY1MmRkMzY0ZDciLCJpc3MiOiJodHRwczovL3Nzby10ZXN0LnB1enpsZS5jaC9hdXRoL3JlYWxtcy9waXRjIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJwaXRjLXNraWxscy1mcm9udGVuZCIsImFjY291bnQiXSwic3ViIjoiMzUyNmIyMDYtYmMzMi00Y2U0LWE2MTQtMWJkN2M2NDg4YWU4IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZmdjIiwibm9uY2UiOiJhc2QiLCJzZXNzaW9uX3N0YXRlIjoiOTUyZTk2NGQtOWZhOC00MGExLTkwYzEtNjdiMmJkNzdmMDhkIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXBpdGMiXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctdXNlcnMiLCJxdWVyeS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIiwicXVlcnktdXNlcnMiXX0sInBpdGMtc2tpbGxzLWZyb250ZW5kIjp7InJvbGVzIjpbIkFETUlOIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiI5NTJlOTY0ZC05ZmE4LTQwYTEtOTBjMS02N2IyYmQ3N2YwOGQiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IllhbmljayBNaW5kZXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ5bWluZGVyIiwiZ2l2ZW5fbmFtZSI6IllhbmljayIsImZhbWlseV9uYW1lIjoiTWluZGVyIiwiZW1haWwiOiJtaW5kZXJAcHV6emxlLmNoIn0.FqAAuk25L33uxEpHCcGuQjO9SxbdHvZD3ghf5BHmhaBPyghO4z1UcfHwtA7BSw1Sfjl_RmG-k9L28hIDDXLHmdJ5JK_4Ic79e69PnhM-1hlTdtTwMx0tSxlO7uh72s3CCGMmQWc2-ZpAKPgeT-HaOGrEEkxEpocG6CFQ2yEVXn5lEleFRZcQNJ83jyi57ELhVrC1Qo96JJyTtlwyHXvCW4AyzUFEjtCaEfek1C2XmJB8TJDi9Wd2qzGgrL4OiO57EvbZP8Emutjx58_rq9mELaWFtdcfHT72IpMAT84vb6qKFy-BIG-FLJe91am4jMK3kAxHG61ATG35Y3FEcjgRDw