#!/bin/bash
set -e

rm -f tmp/pids/server.pid

mkdir -p /opt/bundle /seed /home/app /myapp/.yarn /myapp/node_modules tmp/pids

chown -R app:app /myapp /opt/bundle /seed /home/app

gosu app bundle check || gosu app bundle install
gosu app yarn install

if [ -z "$SKIP_RAILS_MIGRATIONS" ]; then
  echo "⚙️  Performing migrations"
  gosu app bundle exec rails db:create || true
  gosu app bundle exec rails db:migrate
  echo "✅ Migrations done"
fi

if [ -z "$SKIP_RAILS_SEED" ]; then
  if [ ! -f /seed/done ]; then
    echo "⚙️  seeding db"
    gosu app bundle exec rails db:seed
    gosu app bash -c "date > /seed/done"
    echo "✅ seeding done"
  else
    echo "↪️  skipping seeding because already done on $(cat /seed/done)"
  fi
fi

echo "➡️ handing control over to '$*''"

echo "⚙️  executing: $@"
exec gosu app bundle exec "$@"