#!/bin/bash
set -e

rm -f tmp/pids/server.pid

export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$GEM_HOME/bin:$PATH"

  bundle check || bundle install
  yarn install

  if [ -z "$SKIP_RAILS_MIGRATIONS" ]; then
    echo "⚙️  Performing migrations"
    bundle exec rails db:create || true
    bundle exec rails db:migrate
    echo "✅ Migrations done"
  fi

  if [ -z "$SKIP_RAILS_SEED" ]; then
    if [ ! -f /seed/done ]; then
      echo "⚙️  seeding db"
      bundle exec rails db:seed && date > /seed/done
      echo "✅ seeding done"
    else
      echo "↪️  skipping seeding because already done on $(cat /seed/done)"
    fi
  fi

echo "➡️ handing control over to '$*'"
exec bundle exec "$@"