---
apiVersion: v1
kind: ImageStream
metadata:
  name: ruby-slim-upstream
  annotations:
    puzzle.ch/purpose: Upstream image change trigger
spec:
  dockerImageRepository: docker.io
  tags:
    - from:
        kind: DockerImage
        name: docker.io/ruby:2.7-slim
      importPolicy:
        scheduled: true
      name: latest
  lookupPolicy:
    local: true
...
---
apiVersion: v1
kind: ImageStream
metadata:
  name: skills
spec:
  lookupPolicy:
    local: true
...
---
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: skills
  name: skills
spec:
  successfulBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: skills:latest
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 128Mi
  source:
    git:
      ref: master
      uri: https://github.com/puzzle/skills.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      from:
        kind: ImageStreamTag
        name: ruby:2.7-slim
      env:
        - name: TZ
          value: Europe/Zurich
        - name: RAILS_ENV
          value: production
        - name: RAKE_ENV
          value: production
        - name: YARN_VERSION
          value: 1.22.10
        - name: BUNDLER_VERSION
          value: 2.2.16
        - name: BUNDLER_WITHOUT
          value: development test
        - name: BUILD_PACKAGES
          value: figlet cowsay
        - name: RUN_PACKAGES
          value: figlet cowsay
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: secret-key-base
              key: key
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: ruby:2.7-slim
      type: ImageChange
...
